### ISSUE TITLE
Pythonのtestがまだ駄目な件

### ISSUE THREAD

**Issue by shogo314** [rainbou-kpr/library#56]
違いが出そうな原因候補
①
import sys
input = sys.stdin.buffer.readline
が必要
②
importが2行目（# verification-helper: PROBL~の直後）にあるのがよくない
③
importの直前の行になにかあるのがよくない
④
def main()に->Noneが必要

**Comment by shogo314** [comment]
上記のどれでもなさそう
classかどうかで結果が変わっただけ？

**Comment by shogo314** [comment]
標準ライブラリをimportするとバグるっぽいけどmathは問題ない

**Comment by shogo314** [comment]
一部の標準ライブラリをimportしたときに正常に動作しない
正常に動作する

- math
- sys

動作しない

- collections
- heapq

**Comment by KowerKoint** [comment]
collectionsとかが単に複雑すぎてimport解析がタイムアウトしてるっぽいです…
verification-helperのソースコード読んでるとimportlabを使ってるっぽいんですが、僕の手元で`pip install importlab`して`importlab --tree test/yosupo-shortest-path.test.py`とか実行すると15秒くらいかかるんですよね

oj-verifyのimport解析のタイムアウトは1秒 ( https://github.com/online-judge-tools/verification-helper/blob/master/onlinejudge_verify/languages/python.py#L64 )なので明らかに間に合わないです :innocent:

**Comment by shogo314** [comment]
対応ありがとうございます
