### ISSUE TITLE
bipartite graph

### ISSUE THREAD

**Issue by shogo314** [rainbou-kpr/library#96]
グラフのファイルが大きくなるのは嫌いなのでグラフの便利関数を集めたファイルを作ろうと思ってます。

**Comment by shogo314** [comment]
方針（意見があれば言って下さい）
- 二部グラフの判定はDFSで実装
- トポソはそっちのファイルに移す

聞きたいこと
- ファイル名をどうするか

**Comment by KowerKoint** [comment]
pythonのexpanderができてないから余りコピペ回数を増やしたくなくてまとめてるという文脈はありますが、treeもわけてるし分けるのはありだと思います
graph_utilとかでいいんじゃないですかね？

2つに分解した結果は欲しいです
無向グラフの塗り分け関連で言えば連結成分分解もあると嬉しそう

**Comment by shogo314** [comment]
https://github.com/rainbou-kpr/library/pull/97
